<?php

namespace App\DataFixtures;

use App\Entity\CheeseListing;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

final class CheeseListingFixtures extends Fixture {
    public function load(ObjectManager $manager)
    {
        for ($i = 0; $i < 1000; $i++) {
            $cheeseListing = new CheeseListing('Cheese ' . $i);
            $cheeseListing->setPrice(mt_rand(100, 10000));
            $cheeseListing->setIsPublished(true);
            $cheeseListing->setTextDescription('Just a random cheese generated by a fixture class.');
            $manager->persist($cheeseListing);
        }

        $manager->flush();
    }
}